export const YouVersionBookName: { [key: string]: string } = {
  undefined: "GEN",
  Gen: "GEN",
  Exod: "EXO",
  Lev: "LEV",
  Num: "NUM",
  Deut: "DEU",
  Josh: "JOS",
  Judg: "JDG",
  Ruth: "RUT",
  "1 Sam": "1SA",
  "2 Sam": "2SA",
  "1 Kgs": "1KI",
  "2 Kgs": "2KI",
  "1 Chr": "1CH",
  "2 Chr": "2CH",
  Ezra: "EZR",
  Neh: "NEH",
  Esth: "EST",
  Job: "JOB",
  Ps: "PSA",
  Prov: "PRO",
  Eccles: "ECC",
  Song: "SNG",
  Isa: "ISA",
  Jer: "JER",
  Lam: "Lam",
  Ezek: "EZK",
  Dan: "DAN",
  Hos: "HOS",
  Joel: "JOL",
  Amos: "AMO",
  Obad: "OBA",
  Jonah: "JON",
  Mic: "MIC",
  Nah: "NAM",
  Hab: "HAB",
  Zeph: "ZEP",

  Hag: "HAG",
  Zech: "ZEC",
  Mal: "MAL",
  Matt: "MAT",
  Mark: "MRK",
  Luke: "LUK",
  John: "JHN",
  Acts: "ACT",
  Rom: "ROM",
  "1 Cor": "1CO",
  "2 Cor": "2CO",
  Gal: "GAL",
  Eph: "EPH",
  Phil: "PHP",
  Col: "COL",
  "1 Thess": "1TH",
  "2 Thess": "2TH",
  "1 Tim": "1TI",
  "2 Tim": "2TI",
  Titus: "TIT",
  Philem: "PHM",
  Heb: "HEB",
  James: "JAS",
  "1 Pet": "1PE",

  "2 Pet": "2PE",
  "1 John": "1JN",
  "2 John": "2JN",
  "3 John": "3JN",
  Jude: "JUD",
  Rev: "REV",
};
