export const OldTestamentBooks = [
  {
    title: "The Law",
    books: [
      {
        bookName: "Genesis",
        abbreviation: "Gen",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
          { chapterNumber: 43, completed: false },
          { chapterNumber: 44, completed: false },
          { chapterNumber: 45, completed: false },
          { chapterNumber: 46, completed: false },
          { chapterNumber: 47, completed: false },
          { chapterNumber: 48, completed: false },
          { chapterNumber: 49, completed: false },

          { chapterNumber: 50, completed: false },
        ],
      },
      {
        bookName: "Exodus",
        abbreviation: "Exod",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
        ],
      },
      {
        bookName: "Leviticus",
        abbreviation: "Lev",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
        ],
      },
      {
        bookName: "Numbers",
        abbreviation: "Num",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
        ],
      },
      {
        bookName: "Deuteronomy",
        abbreviation: "Deut",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
        ],
      },
    ],
  },
  {
    title: "History",
    books: [
      {
        bookName: "Joshua",
        abbreviation: "Josh",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
        ],
      },
      {
        bookName: "Judges",
        abbreviation: "Judg",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
        ],
      },
      {
        bookName: "Ruth",
        abbreviation: "Ruth",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
        ],
      },
      {
        bookName: "1 Samuel",
        abbreviation: "1 Sam",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
        ],
      },
      {
        bookName: "2 Samuel",
        abbreviation: "2 Sam",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
        ],
      },
      {
        bookName: "1 Kings",
        abbreviation: "1 Kgs",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
        ],
      },
      {
        bookName: "2 Kings",
        abbreviation: "2 Kgs",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
        ],
      },
      {
        bookName: "1 Chronicles",
        abbreviation: "1 Chr",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
        ],
      },
      {
        bookName: "2 Chronicles",
        abbreviation: "2 Chr",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
        ],
      },
      {
        bookName: "Ezra",
        abbreviation: "Ezra",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
        ],
      },
      {
        bookName: "Nehemiah",
        abbreviation: "Neh",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
        ],
      },
      {
        bookName: "Esther",
        abbreviation: "Esth",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
        ],
      },
    ],
  },
  {
    title: "Poetry",
    books: [
      {
        bookName: "Job",
        abbreviation: "Job",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
        ],
      },
      {
        bookName: "Psalms",
        abbreviation: "Ps",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
          { chapterNumber: 43, completed: false },
          { chapterNumber: 44, completed: false },
          { chapterNumber: 45, completed: false },
          { chapterNumber: 46, completed: false },
          { chapterNumber: 47, completed: false },
          { chapterNumber: 48, completed: false },
          { chapterNumber: 49, completed: false },
          { chapterNumber: 50, completed: false },
          { chapterNumber: 51, completed: false },
          { chapterNumber: 52, completed: false },
          { chapterNumber: 53, completed: false },
          { chapterNumber: 54, completed: false },
          { chapterNumber: 55, completed: false },
          { chapterNumber: 56, completed: false },
          { chapterNumber: 57, completed: false },
          { chapterNumber: 58, completed: false },
          { chapterNumber: 59, completed: false },
          { chapterNumber: 60, completed: false },
          { chapterNumber: 61, completed: false },
          { chapterNumber: 62, completed: false },
          { chapterNumber: 63, completed: false },
          { chapterNumber: 64, completed: false },
          { chapterNumber: 65, completed: false },
          { chapterNumber: 66, completed: false },
          { chapterNumber: 67, completed: false },
          { chapterNumber: 68, completed: false },
          { chapterNumber: 69, completed: false },
          { chapterNumber: 70, completed: false },
          { chapterNumber: 71, completed: false },
          { chapterNumber: 72, completed: false },
          { chapterNumber: 73, completed: false },
          { chapterNumber: 74, completed: false },
          { chapterNumber: 75, completed: false },
          { chapterNumber: 76, completed: false },
          { chapterNumber: 77, completed: false },
          { chapterNumber: 78, completed: false },
          { chapterNumber: 79, completed: false },
          { chapterNumber: 80, completed: false },
          { chapterNumber: 81, completed: false },
          { chapterNumber: 82, completed: false },
          { chapterNumber: 83, completed: false },
          { chapterNumber: 84, completed: false },
          { chapterNumber: 85, completed: false },
          { chapterNumber: 86, completed: false },
          { chapterNumber: 87, completed: false },
          { chapterNumber: 88, completed: false },
          { chapterNumber: 89, completed: false },
          { chapterNumber: 90, completed: false },
          { chapterNumber: 91, completed: false },
          { chapterNumber: 92, completed: false },
          { chapterNumber: 93, completed: false },
          { chapterNumber: 94, completed: false },
          { chapterNumber: 95, completed: false },
          { chapterNumber: 96, completed: false },
          { chapterNumber: 97, completed: false },
          { chapterNumber: 98, completed: false },
          { chapterNumber: 99, completed: false },
          { chapterNumber: 100, completed: false },
          { chapterNumber: 101, completed: false },
          { chapterNumber: 102, completed: false },
          { chapterNumber: 103, completed: false },
          { chapterNumber: 104, completed: false },
          { chapterNumber: 105, completed: false },
          { chapterNumber: 106, completed: false },
          { chapterNumber: 107, completed: false },
          { chapterNumber: 108, completed: false },
          { chapterNumber: 109, completed: false },
          { chapterNumber: 110, completed: false },
          { chapterNumber: 111, completed: false },
          { chapterNumber: 112, completed: false },
          { chapterNumber: 113, completed: false },
          { chapterNumber: 114, completed: false },
          { chapterNumber: 115, completed: false },
          { chapterNumber: 116, completed: false },
          { chapterNumber: 117, completed: false },
          { chapterNumber: 118, completed: false },
          { chapterNumber: 119, completed: false },
          { chapterNumber: 120, completed: false },
          { chapterNumber: 121, completed: false },
          { chapterNumber: 122, completed: false },
          { chapterNumber: 123, completed: false },
          { chapterNumber: 124, completed: false },
          { chapterNumber: 125, completed: false },
          { chapterNumber: 126, completed: false },
          { chapterNumber: 127, completed: false },
          { chapterNumber: 128, completed: false },
          { chapterNumber: 129, completed: false },
          { chapterNumber: 130, completed: false },
          { chapterNumber: 131, completed: false },
          { chapterNumber: 132, completed: false },
          { chapterNumber: 133, completed: false },
          { chapterNumber: 134, completed: false },
          { chapterNumber: 135, completed: false },
          { chapterNumber: 136, completed: false },
          { chapterNumber: 137, completed: false },
          { chapterNumber: 138, completed: false },
          { chapterNumber: 139, completed: false },
          { chapterNumber: 140, completed: false },
          { chapterNumber: 141, completed: false },
          { chapterNumber: 142, completed: false },
          { chapterNumber: 143, completed: false },
          { chapterNumber: 144, completed: false },
          { chapterNumber: 145, completed: false },
          { chapterNumber: 146, completed: false },
          { chapterNumber: 147, completed: false },
          { chapterNumber: 148, completed: false },
          { chapterNumber: 149, completed: false },
          { chapterNumber: 150, completed: false },
        ],
      },
      {
        bookName: "Proverbs",
        abbreviation: "Prov",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
        ],
      },
      {
        bookName: "Ecclesiastes",
        abbreviation: "Eccles",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
        ],
      },
      {
        bookName: "Song of Solomon",
        abbreviation: "Song",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
        ],
      },
    ],
  },
  {
    title: "Major Prophets",
    books: [
      {
        bookName: "Isaiah",
        abbreviation: "Isa",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
          { chapterNumber: 43, completed: false },
          { chapterNumber: 44, completed: false },
          { chapterNumber: 45, completed: false },
          { chapterNumber: 46, completed: false },
          { chapterNumber: 47, completed: false },
          { chapterNumber: 48, completed: false },
          { chapterNumber: 49, completed: false },
          { chapterNumber: 50, completed: false },
          { chapterNumber: 51, completed: false },
          { chapterNumber: 52, completed: false },
          { chapterNumber: 53, completed: false },
          { chapterNumber: 54, completed: false },
          { chapterNumber: 55, completed: false },
          { chapterNumber: 56, completed: false },
          { chapterNumber: 57, completed: false },
          { chapterNumber: 58, completed: false },
          { chapterNumber: 59, completed: false },
          { chapterNumber: 60, completed: false },
          { chapterNumber: 61, completed: false },
          { chapterNumber: 62, completed: false },
          { chapterNumber: 63, completed: false },
          { chapterNumber: 64, completed: false },
          { chapterNumber: 65, completed: false },
          { chapterNumber: 66, completed: false },
        ],
      },

      {
        bookName: "Jeremiah",
        abbreviation: "Jer",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
          { chapterNumber: 43, completed: false },
          { chapterNumber: 44, completed: false },
          { chapterNumber: 45, completed: false },
          { chapterNumber: 46, completed: false },
          { chapterNumber: 47, completed: false },
          { chapterNumber: 48, completed: false },
          { chapterNumber: 49, completed: false },

          { chapterNumber: 50, completed: false },
          { chapterNumber: 51, completed: false },
          { chapterNumber: 52, completed: false },
        ],
      },
      {
        bookName: "Lamentations",
        abbreviation: "Lam",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
        ],
      },
      {
        bookName: "Ezekiel",
        abbreviation: "Ezek",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
          { chapterNumber: 15, completed: false },
          { chapterNumber: 16, completed: false },
          { chapterNumber: 17, completed: false },
          { chapterNumber: 18, completed: false },
          { chapterNumber: 19, completed: false },
          { chapterNumber: 20, completed: false },
          { chapterNumber: 21, completed: false },
          { chapterNumber: 22, completed: false },
          { chapterNumber: 23, completed: false },
          { chapterNumber: 24, completed: false },
          { chapterNumber: 25, completed: false },
          { chapterNumber: 26, completed: false },
          { chapterNumber: 27, completed: false },
          { chapterNumber: 28, completed: false },
          { chapterNumber: 29, completed: false },
          { chapterNumber: 30, completed: false },
          { chapterNumber: 31, completed: false },
          { chapterNumber: 32, completed: false },
          { chapterNumber: 33, completed: false },
          { chapterNumber: 34, completed: false },
          { chapterNumber: 35, completed: false },
          { chapterNumber: 36, completed: false },
          { chapterNumber: 37, completed: false },
          { chapterNumber: 38, completed: false },
          { chapterNumber: 39, completed: false },
          { chapterNumber: 40, completed: false },
          { chapterNumber: 41, completed: false },
          { chapterNumber: 42, completed: false },
          { chapterNumber: 43, completed: false },
          { chapterNumber: 44, completed: false },
          { chapterNumber: 45, completed: false },
          { chapterNumber: 46, completed: false },
          { chapterNumber: 47, completed: false },
          { chapterNumber: 48, completed: false },
        ],
      },
      {
        bookName: "Daniel",
        abbreviation: "Dan",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
        ],
      },
    ],
  },
  {
    title: "Minor Prophets",
    books: [
      {
        bookName: "Hosea",
        abbreviation: "Hos",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
        ],
      },
      {
        bookName: "Joel",
        abbreviation: "Joel",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
        ],
      },
      {
        bookName: "Amos",
        abbreviation: "Amos",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },

          { chapterNumber: 9, completed: false },
        ],
      },
      {
        bookName: "Obadiah",
        abbreviation: "Obad",
        inProgress: false,
        finished: false,
        chapters: [{ chapterNumber: 1, completed: false }],
      },
      {
        bookName: "Jonah",
        abbreviation: "Jonah",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
        ],
      },
      {
        bookName: "Micah",
        abbreviation: "Mic",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },

          { chapterNumber: 7, completed: false },
        ],
      },
      {
        bookName: "Nahum",
        abbreviation: "Nah",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
        ],
      },
      {
        bookName: "Habakkuk",
        abbreviation: "Hab",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
        ],
      },
      {
        bookName: "Zephaniah",
        abbreviation: "Zeph",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
        ],
      },
      {
        bookName: "Haggai",
        abbreviation: "Hag",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },

          { chapterNumber: 2, completed: false },
        ],
      },
      {
        bookName: "Zechariah",
        abbreviation: "Zech",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
          { chapterNumber: 5, completed: false },
          { chapterNumber: 6, completed: false },
          { chapterNumber: 7, completed: false },
          { chapterNumber: 8, completed: false },
          { chapterNumber: 9, completed: false },
          { chapterNumber: 10, completed: false },
          { chapterNumber: 11, completed: false },
          { chapterNumber: 12, completed: false },
          { chapterNumber: 13, completed: false },
          { chapterNumber: 14, completed: false },
        ],
      },
      {
        bookName: "Malachi",
        abbreviation: "Mal",
        inProgress: false,
        finished: false,
        chapters: [
          { chapterNumber: 1, completed: false },
          { chapterNumber: 2, completed: false },
          { chapterNumber: 3, completed: false },
          { chapterNumber: 4, completed: false },
        ],
      },
    ],
  },
];
